[package]
name = "coding-game"
version = "0.1.0"
authors = ["ilyavolkov <mormehtar@gmail.com>"]
build = "build.rs"

[build-dependencies]
rustsourcebundler = { git = "https://github.com/lpenz/rust-sourcebundler" }

[dependencies]
